// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: proxy/singbox/config.proto

package singbox

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Config of the "singbox" outbound: traffic routed to it is carried by a sing-box outbound or
// endpoint, so every protocol sing-box speaks is usable from an Xray config — behind Xray's routing,
// DNS, balancers and chains.
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A sing-box configuration fragment, as JSON: the `outbounds` and `endpoints` to run, and any
	// box-wide options they rely on (`dns`, `ntp`, `certificate`, `route.default_domain_resolver`…).
	// Inbounds are not allowed: this box only ever dials out.
	Config string `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// Tag of the outbound or endpoint that carries the traffic. Empty means the first endpoint, or the
	// first outbound when there are no endpoints.
	Use string `protobuf:"bytes,2,opt,name=use,proto3" json:"use,omitempty"`
	// Sends sing-box's own connections to its servers through this Xray outbound's dialer — its
	// sockopt and `dialerProxy` chain — instead of letting sing-box dial them. Only outbounds and
	// endpoints without a `detour` of their own are rerouted.
	ViaXray       bool `protobuf:"varint,3,opt,name=via_xray,json=viaXray,proto3" json:"via_xray,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_proxy_singbox_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_singbox_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_proxy_singbox_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *Config) GetUse() string {
	if x != nil {
		return x.Use
	}
	return ""
}

func (x *Config) GetViaXray() bool {
	if x != nil {
		return x.ViaXray
	}
	return false
}

var File_proxy_singbox_config_proto protoreflect.FileDescriptor

const file_proxy_singbox_config_proto_rawDesc = "" +
	"\n" +
	"\x1aproxy/singbox/config.proto\x12\x12xray.proxy.singbox\"M\n" +
	"\x06Config\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\x12\x10\n" +
	"\x03use\x18\x02 \x01(\tR\x03use\x12\x19\n" +
	"\bvia_xray\x18\x03 \x01(\bR\aviaXrayBX\n" +
	"\x16com.xray.proxy.singboxP\x01Z'github.com/xtls/xray-core/proxy/singbox\xaa\x02\x12Xray.Proxy.Singboxb\x06proto3"

var (
	file_proxy_singbox_config_proto_rawDescOnce sync.Once
	file_proxy_singbox_config_proto_rawDescData []byte
)

func file_proxy_singbox_config_proto_rawDescGZIP() []byte {
	file_proxy_singbox_config_proto_rawDescOnce.Do(func() {
		file_proxy_singbox_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_singbox_config_proto_rawDesc), len(file_proxy_singbox_config_proto_rawDesc)))
	})
	return file_proxy_singbox_config_proto_rawDescData
}

var file_proxy_singbox_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proxy_singbox_config_proto_goTypes = []any{
	(*Config)(nil), // 0: xray.proxy.singbox.Config
}
var file_proxy_singbox_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proxy_singbox_config_proto_init() }
func file_proxy_singbox_config_proto_init() {
	if File_proxy_singbox_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_singbox_config_proto_rawDesc), len(file_proxy_singbox_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_singbox_config_proto_goTypes,
		DependencyIndexes: file_proxy_singbox_config_proto_depIdxs,
		MessageInfos:      file_proxy_singbox_config_proto_msgTypes,
	}.Build()
	File_proxy_singbox_config_proto = out.File
	file_proxy_singbox_config_proto_goTypes = nil
	file_proxy_singbox_config_proto_depIdxs = nil
}
