// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: proxy/autoselect/config.proto

package autoselect

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Config of the "autoselect" outbound: a group that forwards every connection through the
// healthiest of its member outbounds, fails over without the client noticing, and keeps probing
// the members so it knows where to go next.
//
// Durations are milliseconds. Every zero value means "use the built-in default", which is why the
// switches are phrased as disable_* — a proto3 bool cannot tell "unset" from "false".
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Member outbound tags, in the caller's order of preference. Ties in health are broken by it.
	Outbounds []string `protobuf:"bytes,1,rep,name=outbounds,proto3" json:"outbounds,omitempty"`
	// Tag prefixes resolved against the outbound manager at runtime, appended after `outbounds`.
	Selector []string `protobuf:"bytes,2,rep,name=selector,proto3" json:"selector,omitempty"`
	ProbeUrl string   `protobuf:"bytes,3,opt,name=probe_url,json=probeUrl,proto3" json:"probe_url,omitempty"`
	// Tried once when a probe of probe_url fails, so a member whose own routing blocks the probe
	// host is not declared dead.
	FallbackProbeUrl string `protobuf:"bytes,4,opt,name=fallback_probe_url,json=fallbackProbeUrl,proto3" json:"fallback_probe_url,omitempty"`
	ProbeTimeoutMs   int64  `protobuf:"varint,5,opt,name=probe_timeout_ms,json=probeTimeoutMs,proto3" json:"probe_timeout_ms,omitempty"`
	// How often the selected member is probed while traffic flows. Skipped whenever real traffic
	// through it succeeded within the same interval.
	ActiveIntervalMs int64 `protobuf:"varint,6,opt,name=active_interval_ms,json=activeIntervalMs,proto3" json:"active_interval_ms,omitempty"`
	// How often the best alternatives (the failover targets) are probed.
	StandbyIntervalMs int64 `protobuf:"varint,7,opt,name=standby_interval_ms,json=standbyIntervalMs,proto3" json:"standby_interval_ms,omitempty"`
	StandbyCount      int32 `protobuf:"varint,8,opt,name=standby_count,json=standbyCount,proto3" json:"standby_count,omitempty"`
	// How often every other member is probed.
	SweepIntervalMs int64 `protobuf:"varint,9,opt,name=sweep_interval_ms,json=sweepIntervalMs,proto3" json:"sweep_interval_ms,omitempty"`
	// No connection for this long pauses probing until traffic resumes.
	IdleAfterMs int64 `protobuf:"varint,10,opt,name=idle_after_ms,json=idleAfterMs,proto3" json:"idle_after_ms,omitempty"`
	// A healthy selection is only replaced by a member that is at least this much faster
	// (0.3 = 30%) AND by at least switch_min_gain_ms, and only after min_dwell_ms on the current one.
	SwitchRatio     float32 `protobuf:"fixed32,11,opt,name=switch_ratio,json=switchRatio,proto3" json:"switch_ratio,omitempty"`
	SwitchMinGainMs int64   `protobuf:"varint,12,opt,name=switch_min_gain_ms,json=switchMinGainMs,proto3" json:"switch_min_gain_ms,omitempty"`
	MinDwellMs      int64   `protobuf:"varint,13,opt,name=min_dwell_ms,json=minDwellMs,proto3" json:"min_dwell_ms,omitempty"`
	// Transparent retry of a failed connection on the next member.
	DisableRetry bool  `protobuf:"varint,14,opt,name=disable_retry,json=disableRetry,proto3" json:"disable_retry,omitempty"`
	MaxAttempts  int32 `protobuf:"varint,15,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	// Upper bound of client data kept for replaying a connection onto another member.
	MaxReplayBytes int32 `protobuf:"varint,16,opt,name=max_replay_bytes,json=maxReplayBytes,proto3" json:"max_replay_bytes,omitempty"`
	// First response budget of an attempt; 0 derives it from the member's measured delay.
	AttemptBudgetMs int64 `protobuf:"varint,17,opt,name=attempt_budget_ms,json=attemptBudgetMs,proto3" json:"attempt_budget_ms,omitempty"`
	// Member to start on before any probe has answered (the caller's cached best).
	Initial string `protobuf:"bytes,18,opt,name=initial,proto3" json:"initial,omitempty"`
	// Leave connections that stopped receiving data on a member that was found dead alone.
	DisableInterruptStalled bool  `protobuf:"varint,19,opt,name=disable_interrupt_stalled,json=disableInterruptStalled,proto3" json:"disable_interrupt_stalled,omitempty"`
	Concurrency             int32 `protobuf:"varint,20,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_proxy_autoselect_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_autoselect_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_proxy_autoselect_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetOutbounds() []string {
	if x != nil {
		return x.Outbounds
	}
	return nil
}

func (x *Config) GetSelector() []string {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *Config) GetProbeUrl() string {
	if x != nil {
		return x.ProbeUrl
	}
	return ""
}

func (x *Config) GetFallbackProbeUrl() string {
	if x != nil {
		return x.FallbackProbeUrl
	}
	return ""
}

func (x *Config) GetProbeTimeoutMs() int64 {
	if x != nil {
		return x.ProbeTimeoutMs
	}
	return 0
}

func (x *Config) GetActiveIntervalMs() int64 {
	if x != nil {
		return x.ActiveIntervalMs
	}
	return 0
}

func (x *Config) GetStandbyIntervalMs() int64 {
	if x != nil {
		return x.StandbyIntervalMs
	}
	return 0
}

func (x *Config) GetStandbyCount() int32 {
	if x != nil {
		return x.StandbyCount
	}
	return 0
}

func (x *Config) GetSweepIntervalMs() int64 {
	if x != nil {
		return x.SweepIntervalMs
	}
	return 0
}

func (x *Config) GetIdleAfterMs() int64 {
	if x != nil {
		return x.IdleAfterMs
	}
	return 0
}

func (x *Config) GetSwitchRatio() float32 {
	if x != nil {
		return x.SwitchRatio
	}
	return 0
}

func (x *Config) GetSwitchMinGainMs() int64 {
	if x != nil {
		return x.SwitchMinGainMs
	}
	return 0
}

func (x *Config) GetMinDwellMs() int64 {
	if x != nil {
		return x.MinDwellMs
	}
	return 0
}

func (x *Config) GetDisableRetry() bool {
	if x != nil {
		return x.DisableRetry
	}
	return false
}

func (x *Config) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *Config) GetMaxReplayBytes() int32 {
	if x != nil {
		return x.MaxReplayBytes
	}
	return 0
}

func (x *Config) GetAttemptBudgetMs() int64 {
	if x != nil {
		return x.AttemptBudgetMs
	}
	return 0
}

func (x *Config) GetInitial() string {
	if x != nil {
		return x.Initial
	}
	return ""
}

func (x *Config) GetDisableInterruptStalled() bool {
	if x != nil {
		return x.DisableInterruptStalled
	}
	return false
}

func (x *Config) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

var File_proxy_autoselect_config_proto protoreflect.FileDescriptor

const file_proxy_autoselect_config_proto_rawDesc = "" +
	"\n" +
	"\x1dproxy/autoselect/config.proto\x12\x15xray.proxy.autoselect\"\x92\x06\n" +
	"\x06Config\x12\x1c\n" +
	"\toutbounds\x18\x01 \x03(\tR\toutbounds\x12\x1a\n" +
	"\bselector\x18\x02 \x03(\tR\bselector\x12\x1b\n" +
	"\tprobe_url\x18\x03 \x01(\tR\bprobeUrl\x12,\n" +
	"\x12fallback_probe_url\x18\x04 \x01(\tR\x10fallbackProbeUrl\x12(\n" +
	"\x10probe_timeout_ms\x18\x05 \x01(\x03R\x0eprobeTimeoutMs\x12,\n" +
	"\x12active_interval_ms\x18\x06 \x01(\x03R\x10activeIntervalMs\x12.\n" +
	"\x13standby_interval_ms\x18\a \x01(\x03R\x11standbyIntervalMs\x12#\n" +
	"\rstandby_count\x18\b \x01(\x05R\fstandbyCount\x12*\n" +
	"\x11sweep_interval_ms\x18\t \x01(\x03R\x0fsweepIntervalMs\x12\"\n" +
	"\ridle_after_ms\x18\n" +
	" \x01(\x03R\vidleAfterMs\x12!\n" +
	"\fswitch_ratio\x18\v \x01(\x02R\vswitchRatio\x12+\n" +
	"\x12switch_min_gain_ms\x18\f \x01(\x03R\x0fswitchMinGainMs\x12 \n" +
	"\fmin_dwell_ms\x18\r \x01(\x03R\n" +
	"minDwellMs\x12#\n" +
	"\rdisable_retry\x18\x0e \x01(\bR\fdisableRetry\x12!\n" +
	"\fmax_attempts\x18\x0f \x01(\x05R\vmaxAttempts\x12(\n" +
	"\x10max_replay_bytes\x18\x10 \x01(\x05R\x0emaxReplayBytes\x12*\n" +
	"\x11attempt_budget_ms\x18\x11 \x01(\x03R\x0fattemptBudgetMs\x12\x18\n" +
	"\ainitial\x18\x12 \x01(\tR\ainitial\x12:\n" +
	"\x19disable_interrupt_stalled\x18\x13 \x01(\bR\x17disableInterruptStalled\x12 \n" +
	"\vconcurrency\x18\x14 \x01(\x05R\vconcurrencyBa\n" +
	"\x19com.xray.proxy.autoselectP\x01Z*github.com/xtls/xray-core/proxy/autoselect\xaa\x02\x15Xray.Proxy.Autoselectb\x06proto3"

var (
	file_proxy_autoselect_config_proto_rawDescOnce sync.Once
	file_proxy_autoselect_config_proto_rawDescData []byte
)

func file_proxy_autoselect_config_proto_rawDescGZIP() []byte {
	file_proxy_autoselect_config_proto_rawDescOnce.Do(func() {
		file_proxy_autoselect_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_autoselect_config_proto_rawDesc), len(file_proxy_autoselect_config_proto_rawDesc)))
	})
	return file_proxy_autoselect_config_proto_rawDescData
}

var file_proxy_autoselect_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proxy_autoselect_config_proto_goTypes = []any{
	(*Config)(nil), // 0: xray.proxy.autoselect.Config
}
var file_proxy_autoselect_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proxy_autoselect_config_proto_init() }
func file_proxy_autoselect_config_proto_init() {
	if File_proxy_autoselect_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_autoselect_config_proto_rawDesc), len(file_proxy_autoselect_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_autoselect_config_proto_goTypes,
		DependencyIndexes: file_proxy_autoselect_config_proto_depIdxs,
		MessageInfos:      file_proxy_autoselect_config_proto_msgTypes,
	}.Build()
	File_proxy_autoselect_config_proto = out.File
	file_proxy_autoselect_config_proto_goTypes = nil
	file_proxy_autoselect_config_proto_depIdxs = nil
}
